version: '3.7'

services:
  pypi-server:
    image: sscsctf/levels:ctf-id-pypiserver
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./pypiserver/auth
        target: /data/auth
    command: -P /data/auth/.htpasswd -a update,download,list /data/packages
    networks:
      - id-ctf
    restart: always
  attacker:
    image: sscsctf/levels:ctf-id-attacker
    container_name: attacker-container
    networks:
      - id-ctf
  victim:
    image: sscsctf/levels:ctf-id-victim
    container_name: victim-container
    networks:
      - id-ctf
volumes:
  pypiserver:

networks:
  id-ctf:
    external: false

