version: '3'
networks:
  gitea:
    external: false
services:
  server:
    image: sscsctf/levels:ctf-cda-gitea
    container_name: gitea
    restart: always
    networks:
      - gitea
    ports:
      - '5000:80'
      - '2222:22'
  organization:
    image: sscsctf/levels:ctf-cda-organization
    container_name: organization
    networks:
      - gitea
    ports:
      - "3010:80"
  player:
    image: sscsctf/levels:ctf-cda-player
    container_name: player
    hostname: ubuntu
    networks:
      - gitea
    tty: true
    ports:
      - "3020:3020"
