version: '3'
networks:
  gitea:
    external: false
services:
  server:
    image: gitea
    container_name: gitea
    restart: always
    networks:
      - gitea
    ports:
      - '3000:80'
      - '222:22'
    depends_on:
      - db
  db:
    image: db
    restart: always
    networks:
      - gitea
  organization:
    image: organization
    container_name: organization
    networks:
      - gitea
    ports:
      - "3010:3010"
