version: '3.7'

services:
  pypi-server:
    build:
      context: .
      dockerfile: pypi.Dockerfile
    ports:
      - 8000:8080
    restart: always
  internal-server:
    build:
      context: .
      dockerfile: private.Dockerfile
    ports:
      - 8080:8080
    restart: always
  ubuntu:
     build: 
       context: .
       dockerfile: client.Dockerfile
     stdin_open: true
     tty: true

