version: '3.7'

services:
  pypi-server:
    image: sscsctf/levels:confused-dependencies-public
    ports:
      - 8000:8080
    restart: always
  internal-server:
    image: sscsctf/levels:confused-dependencies-internal
    ports:
      - 8080:8080
    restart: always
  client:
    image: sscsctf/levels:confused-dependencies-client
    stdin_open: true
    tty: true

